/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACard: typeof import('@arco-design/web-vue')['Card']
    ACollapse: typeof import('@arco-design/web-vue')['Collapse']
    ACollapseItem: typeof import('@arco-design/web-vue')['CollapseItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    AList: typeof import('@arco-design/web-vue')['List']
    AListItem: typeof import('@arco-design/web-vue')['ListItem']
    APageHeader: typeof import('@arco-design/web-vue')['PageHeader']
    APopconfirm: typeof import('@arco-design/web-vue')['Popconfirm']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ATypography: typeof import('@arco-design/web-vue')['Typography']
    ConfigPreview: typeof import('./src/components/ConfigPreview.vue')['default']
    IconCopy: typeof import('@arco-design/web-vue/es/icon')['IconCopy']
    IconDelete: typeof import('@arco-design/web-vue/es/icon')['IconDelete']
    IconPlus: typeof import('@arco-design/web-vue/es/icon')['IconPlus']
    RouteList: typeof import('./src/components/RouteList.vue')['default']
  }
}
